topics:
  gps: smartcito.gps.raw
  cctv: smartcito.cctv.raw
  iot: smartcito.iot.raw
  alerts: smartcito.alerts
  raw_events: smartcito.events.raw
  clean_events: smartcito.events.clean
  sensor_readings: smartcito.sensors.raw