apiVersion: v1
kind: ConfigMap
metadata:
  name: smartcito-platform-config
  namespace: backend
data:
  HDFS_ENABLED: "false"
  HBASE_ENABLED: "false"
  OBJECT_STORAGE_ENDPOINT: file:///app/data/object_storage