"""initial schema — sensor_readings table

Revision ID: 0001_initial
Revises:
Create Date: 2026-05-20 00:00:00.000000

Purpose:
    Bootstrap the relational schema for SmartCito. Creates the
    `sensor_readings` time-series table that mirrors
    `app.db.models.SensorReadingORM`.

    Hand-written (rather than autogenerated) so this file is reviewable
    and lives in version control before any database exists.
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import JSON, UUID

# revision identifiers, used by Alembic.
revision: str = "0001_initial"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "sensor_readings",
        sa.Column("id", UUID(as_uuid=True), primary_key=True, nullable=False),
        sa.Column("sensor_id", sa.String(length=128), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("unit", sa.String(length=32), nullable=False),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "received_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "extra",
            JSON(),
            nullable=False,
            server_default=sa.text("'{}'::json"),
        ),
    )
    op.create_index("ix_sensor_readings_sensor_id", "sensor_readings", ["sensor_id"])
    op.create_index("ix_sensor_readings_kind", "sensor_readings", ["kind"])
    op.create_index(
        "ix_sensor_readings_sensor_observed",
        "sensor_readings",
        ["sensor_id", "observed_at"],
    )


def downgrade() -> None:
    op.drop_index("ix_sensor_readings_sensor_observed", table_name="sensor_readings")
    op.drop_index("ix_sensor_readings_kind", table_name="sensor_readings")
    op.drop_index("ix_sensor_readings_sensor_id", table_name="sensor_readings")
    op.drop_table("sensor_readings")
