apiVersion: v1
kind: Namespace
metadata:
  labels:
    smartcito.io/tier: backend
  name: ingestion
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    smartcito.io/tier: ai
  name: ai
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    smartcito.io/tier: security
  name: security
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    smartcito.io/tier: visualization
  name: visualization
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    smartcito.io/tier: backend
  name: backend
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    smartcito.io/tier: data-platform
  name: data-platform
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    smartcito.io/tier: database
  name: database
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    smartcito.io/tier: observability
  name: observability
