apiVersion: v1
kind: ResourceQuota
metadata:
  name: security-quota
  namespace: security
spec:
  hard:
    pods: "20"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: default-limits
  namespace: security
spec:
  limits:
    - type: Container
      default:
        cpu: "500m"
        memory: 512Mi
