clouds:
  openstack:
    auth:
      auth_url: http://172.27.112.36/identity/v3
      username: admin
      password: change-me
      project_id: b4e15aaf3bcd41c69934f585febaa845
      project_name: demo
      user_domain_name: Default
    region_name: RegionOne
    interface: public
    identity_api_version: 3